version: '3.7'
 
services:
  mariadb:
    image: mariadb:10.4
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data:
